---
title: "Data Wrangling with R [Part 1]{.part-label}"
date: 2024/04/08
categories: BDSI Workshop
engine: knitr
---


## 👋 Welcome 

This is a training workshop for staff and students affiliated with the Australian National University (ANU) offered by the ANU Biological Data Science Institute (BDSI).

The workshop aims to teach data wrangling with R using the Tidyverse paradigm. Tidyverse is a popular collection of open source packages that share an underlying design philosophy, grammar and data structure.  This workshop is tailored for beginners in the Tidyverse, specifically those with minimal or no exposure to the dplyr and tidyr packages. A basic understanding of R is assumed. Individuals with no prior R knowledge are advised to attend the Introduction to R Programming workshop prior to this workshop. Please do not enrol in this workshop if you have no R knowledge at the start of this workshop.

## 🎯 Learning objectives 

Upon completion of the workshop, participants should be able to

{{< include slides/_learning-objectives.qmd >}}

## 🔧 Preperation 

Please ensure that you download and install 

- the latest version of [R](https://cran.csiro.au/),
- the latest version of [RStudio Desktop](https://posit.co/download/rstudio-desktop/), 
- [Slack](https://slack.com/intl/en-au) (alternatively you can use the web version), and 
- the following packages by opening RStudio Desktop, then copy and paste the command below in the Console section, pushing Enter after pasting.

```r
install.packages(c("tidyverse", "rmarkdown", "janitor", "agridat"))
```

{{< fa hand-holding-medical >}} If you are having issues, see also [here](https://learnr.numbat.space/chapter1) or talk to the teaching team.

::: {.callout-note icon=false style="width:100%"}

## <i class='fab fa-slack'></i> [Slack workspace]{#slack}

::: w-100

[<button class="button">Join ANU Learning Data Slack Community</button>](https://join.slack.com/t/anulearningdata/signup){.no-decoration}

:::

- You must use your ANU email to sign up. 
- Use your full name. 
- By joining, you agree to abide by this [**code of conduct**](/slack.html).

:::

## 👩‍🏫 Teaching team 

`r photo_path <- "slides/"`

{{< include slides/_team.qmd >}}